/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MockTest = IDL.Record({
  'id' : IDL.Nat,
  'maxScore' : IDL.Nat,
  'score' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'examName' : IDL.Text,
});
export const StudySession = IDL.Record({
  'id' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'notStarted' : IDL.Null,
    'done' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'name' : IDL.Text,
  'subjectId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'addTopic' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMockTest' : IDL.Func([IDL.Nat], [], []),
  'deleteStudySession' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'deleteTopic' : IDL.Func([IDL.Nat], [], []),
  'getAllMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
  'getAllStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getAllSubjectsDetailed' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Subject, IDL.Vec(Topic)))],
      ['query'],
    ),
  'getAllSubjectsWithTopics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Subject, IDL.Vec(Topic)))],
      ['query'],
    ),
  'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMockTestsByExamName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MockTest)],
      ['query'],
    ),
  'getMockTestsByScoreRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(MockTest)],
      ['query'],
    ),
  'getSessionsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'getSessionsBySubject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'getSubject' : IDL.Func([IDL.Nat], [Subject], ['query']),
  'getTopicCompletionPercentage' : IDL.Func([], [IDL.Float64], ['query']),
  'getTopicsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
  'getTotalStudyHours' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logStudySession' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'recordMockTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMockTest' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateStudySession' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updateTopic' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updateTopicStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'notStarted' : IDL.Null,
          'done' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MockTest = IDL.Record({
    'id' : IDL.Nat,
    'maxScore' : IDL.Nat,
    'score' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'examName' : IDL.Text,
  });
  const StudySession = IDL.Record({
    'id' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'notStarted' : IDL.Null,
      'done' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'name' : IDL.Text,
    'subjectId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'addTopic' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMockTest' : IDL.Func([IDL.Nat], [], []),
    'deleteStudySession' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'deleteTopic' : IDL.Func([IDL.Nat], [], []),
    'getAllMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
    'getAllStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getAllSubjectsDetailed' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Subject, IDL.Vec(Topic)))],
        ['query'],
      ),
    'getAllSubjectsWithTopics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Subject, IDL.Vec(Topic)))],
        ['query'],
      ),
    'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMockTestsByExamName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MockTest)],
        ['query'],
      ),
    'getMockTestsByScoreRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(MockTest)],
        ['query'],
      ),
    'getSessionsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getSessionsBySubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getSubject' : IDL.Func([IDL.Nat], [Subject], ['query']),
    'getTopicCompletionPercentage' : IDL.Func([], [IDL.Float64], ['query']),
    'getTopicsBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Topic)], ['query']),
    'getTotalStudyHours' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logStudySession' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'recordMockTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMockTest' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateStudySession' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'updateTopic' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'updateTopicStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'notStarted' : IDL.Null,
            'done' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };