/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MockTest {
  'id' : bigint,
  'maxScore' : bigint,
  'score' : bigint,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'examName' : string,
}
export interface StudySession {
  'id' : bigint,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
  'notes' : [] | [string],
  'timestamp' : bigint,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'description' : [] | [string],
}
export interface Topic {
  'id' : bigint,
  'status' : { 'notStarted' : null } |
    { 'done' : null } |
    { 'inProgress' : null },
  'name' : string,
  'subjectId' : bigint,
  'notes' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubject' : ActorMethod<[string, [] | [string]], bigint>,
  'addTopic' : ActorMethod<[bigint, string, [] | [string]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMockTest' : ActorMethod<[bigint], undefined>,
  'deleteStudySession' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'deleteTopic' : ActorMethod<[bigint], undefined>,
  'getAllMockTests' : ActorMethod<[], Array<MockTest>>,
  'getAllStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getAllSubjectsDetailed' : ActorMethod<[], Array<[Subject, Array<Topic>]>>,
  'getAllSubjectsWithTopics' : ActorMethod<[], Array<[Subject, Array<Topic>]>>,
  'getAllTopics' : ActorMethod<[], Array<Topic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMockTestsByExamName' : ActorMethod<[string], Array<MockTest>>,
  'getMockTestsByScoreRange' : ActorMethod<[bigint, bigint], Array<MockTest>>,
  'getSessionsByDateRange' : ActorMethod<[bigint, bigint], Array<StudySession>>,
  'getSessionsBySubject' : ActorMethod<[bigint], Array<StudySession>>,
  'getSubject' : ActorMethod<[bigint], Subject>,
  'getTopicCompletionPercentage' : ActorMethod<[], number>,
  'getTopicsBySubject' : ActorMethod<[bigint], Array<Topic>>,
  'getTotalStudyHours' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logStudySession' : ActorMethod<[bigint, bigint, [] | [string]], bigint>,
  'recordMockTest' : ActorMethod<
    [string, bigint, bigint, [] | [string]],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMockTest' : ActorMethod<
    [bigint, bigint, bigint, [] | [string]],
    undefined
  >,
  'updateStudySession' : ActorMethod<
    [bigint, bigint, [] | [string]],
    undefined
  >,
  'updateSubject' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'updateTopic' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'updateTopicStatus' : ActorMethod<
    [
      bigint,
      { 'notStarted' : null } |
        { 'done' : null } |
        { 'inProgress' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];